# makefile written using https://yuukidach.github.io/p/makefile-for-projects-with-subdirectories/ as template 

TARGET = r-source

OUTDIR = ./build

# includes all src dirs excluding R/
SRCDIR = ./demo ./inst/stan ./inst/stan/include ./man-roxygen ./vignettes
##DIR_OBJ = ./obj

OUTDIR_ABS=$(abspath $(OUTDIR))
PROJROOT_ABS=$(abspath .)


# html doc targets
HTML_DOC_DIR = inst/doc_html
RDS    = $(wildcard man/*.Rd)
HTMLS  = $(patsubst man/%.Rd,$(HTML_DOC_DIR)/%.html,$(RDS))

RPKG=$(patsubst ‘%’, %, $(word 2, $(shell grep ^Package: DESCRIPTION)))
INCS = 
R_PKG_SRCS = $(wildcard R/*.R inst/examples/*R tests/testthat/*R)
R_SRCS = $(wildcard *.R $(foreach fd, $(SRCDIR), $(fd)/*.R))
R_TEST_SRCS = $(wildcard tests/testthat/test*.R)
R_TEST_OBJS = $(R_TEST_SRCS:.R=.Rtest)
R_TESTFAST_OBJS = $(R_TEST_SRCS:.R=.Rtestfast)
FIXTURE_SRCS = $(wildcard tests/testthat/fixtures-src/*_fixture.R)
FIXTURE_OBJS = $(patsubst tests/testthat/fixtures-src/%_fixture.R,tests/testthat/fixtures/%.rds,$(FIXTURE_SRCS))
RMD_SRCS = $(wildcard *.Rmd $(foreach fd, $(SRCDIR), $(fd)/x*.Rmd))
STAN_SRCS = $(wildcard *.stan $(foreach fd, $(SRCDIR), $(fd)/*.stan))
SRCS = $(R_PKG_SRCS) $(R_SRCS) $(RMD_SRCS) $(STAN_SRCS)
NODIR_SRC = $(notdir $(SRCS))
BIN_OBJS = src/package-binary R/sysdata.rda
VIGNETTE_BIB = vignettes/references.bib
DOC_OBJS = man/package-doc inst/doc/$(RPKG).pdf $(VIGNETTE_BIB)
RCMD ?= R_PROFILE_USER="$(PROJROOT_ABS)/.Rprofile" "${R_HOME}/bin/R" -q

R_HOME ?= $(shell R RHOME)
PKG_VERSION ?= $(patsubst ‘%’, %, $(word 2, $(shell grep ^Version DESCRIPTION)))
GIT_TAG ?= v$(PKG_VERSION)

MD5 ?= md5sum
TMPDIR := $(realpath $(shell mktemp -d))

all : $(TARGET)

inst/doc_html/%.html : man/%.Rd
	"${R_HOME}/bin/R" --vanilla --slave -e 'tools::Rd2HTML("$<", out="$@")'

# Single-source bibliography: vignettes/references.bib is a GENERATED copy of
# inst/REFERENCES.bib (the single source of truth for all references, also used
# by Rdpack for the Rd help pages). It is committed so that pkgdown and
# R CMD build (which do not run this rule) can render the vignettes/articles,
# and it is refreshed here so it never drifts from the master file.
$(VIGNETTE_BIB) : inst/REFERENCES.bib
	@echo '% !! GENERATED FILE - DO NOT EDIT BY HAND !!' > $@
	@echo '% This is an auto-generated copy of inst/REFERENCES.bib.' >> $@
	@echo '% The single source of truth is inst/REFERENCES.bib; edit that file' >> $@
	@echo '% and run `make vignettes/references.bib` (also run by `make doc`).' >> $@
	@echo '%' >> $@
	@echo '' >> $@
	@cat $< >> $@
	@echo "Regenerated $@ from inst/REFERENCES.bib"

# Guard against a stale committed copy (skips the 6-line generated header).
check-bib :
	@tail -n +7 $(VIGNETTE_BIB) | diff - inst/REFERENCES.bib > /dev/null \
	  || { echo "ERROR: $(VIGNETTE_BIB) is out of sync with inst/REFERENCES.bib. Run 'make $(VIGNETTE_BIB)'."; exit 1; }
	@echo "$(VIGNETTE_BIB) is in sync with inst/REFERENCES.bib"

# tell makefile how to turn a Rmd into an md file
%.md : %.Rmd
	cd $(@D); echo running $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::md_document(variant='markdown'))"
	cd $(@D); $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::md_document(variant='markdown'))"

%.md : %.R
	cd $(@D); echo running $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::md_document(variant='markdown'))"
	cd $(@D); $(RCMD) -q -e "rmarkdown::render('$(<F)', output_format=rmarkdown::md_document(variant='markdown'))"

# render an html via the respective md file
%.html : %.Rmd
	cd $(@D); echo running $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::html_document(self_contained=TRUE))"
	cd $(@D); $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::html_document(self_contained=TRUE))"

tests/%.Rtest : tests/%.R $(R_PKG_SRCS) NAMESPACE $(FIXTURE_OBJS) tools/run-test-file.R
	NOT_CRAN=true $(RCMD) --slave --file=tools/run-test-file.R --args $< > $@ 2>&1
	@printf "Test summary for $(<F): "
	@grep '^\[' $@ | tail -n 1

tests/%.Rtestfast : tests/%.R $(R_PKG_SRCS) NAMESPACE tools/run-test-file.R
	NOT_CRAN=false $(RCMD) --slave --file=tools/run-test-file.R --args $< > $@ 2>&1
	@printf "Test summary for $(<F): "
	@grep '^\[' $@ | tail -n 1

tests/testthat/fixtures/%.rds : tests/testthat/fixtures-src/%_fixture.R tools/build-test-fixture.R $(R_PKG_SRCS) NAMESPACE
	install -d $(@D)
	FIXTURE_FORCE=$(FIXTURE_FORCE) $(RCMD) --slave --file=tools/build-test-fixture.R --args $< $@


R/stanmodels.R: $(STAN_SRCS)
	## ensure that NAMESPACE contains load directive
	echo "# Generated by roxygen2: do not edit by hand" > NAMESPACE
	echo "import(Rcpp)" >> NAMESPACE
	echo "import(methods)" >> NAMESPACE
	echo "importFrom(rstan, sampling)" >> NAMESPACE
	echo "useDynLib($(RPKG), .registration = TRUE)" >> NAMESPACE
	install -d src
	"${R_HOME}/bin/Rscript" -e "rstantools::rstan_config()"
	touch R/stanmodels.R

src/package-binary: R/stanmodels.R
	## ensure that NAMESPACE contains load directive
	echo "# Generated by roxygen2: do not edit by hand" > NAMESPACE
	echo "import(Rcpp)" >> NAMESPACE
	echo "import(methods)" >> NAMESPACE
	echo "importFrom(rstan, sampling)" >> NAMESPACE
	echo "useDynLib($(RPKG), .registration = TRUE)" >> NAMESPACE
	install -d src
	"${R_HOME}/bin/Rscript" -e 'pkgbuild::compile_dll(debug=FALSE)'
	touch src/package-binary

man/package-doc: $(R_PKG_SRCS) $(BIN_OBJS)
	"${R_HOME}/bin/Rscript" -e 'roxygen2::roxygenize()'
	touch man/package-doc

inst/sbc/sbc_report.html : inst/sbc/sbc_report.R inst/sbc/calibration.rds
	cd $(@D); echo running $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::html_vignette(self_contained=TRUE))"
	cd $(@D); $(RCMD) -e "rmarkdown::render('$(<F)', output_format=rmarkdown::html_vignette(self_contained=TRUE))"

inst/sbc/calibration.rds :
	echo "Please run inst/sbc/make_reference_rankhist.R"
	exit 1

R/sysdata.rda: inst/sbc/calibration.rds
	"${R_HOME}/bin/R" --slave --file=tools/make-ds.R

inst/doc/$(RPKG).pdf : man/package-doc
	install -d inst/doc
	"${R_HOME}/bin/R" CMD Rd2pdf --batch --no-preview --force --output=inst/doc/$(RPKG).pdf .
	"${R_HOME}/bin/R" --vanilla --slave -e 'library(tools); tools::compactPDF("inst/doc/$(RPKG).pdf")'

man/%.Rd : man/package-doc

NAMESPACE: man/package-doc


PHONY := $(TARGET)
$(TARGET): build/r-source-fast

build/r-source-fast : $(BIN_OBJS) $(DOC_OBJS) $(SRCS)
	install -d build
	git archive --format=tar.gz --prefix $(RPKG)-$(GIT_TAG)/ HEAD > build/$(RPKG)-$(GIT_TAG).tar.gz
	rm -rf build/$(RPKG)-$(GIT_TAG)
	cd build; tar x -C $(TMPDIR) -f $(RPKG)-$(GIT_TAG).tar.gz
	rm -f build/$(RPKG)-$(GIT_TAG).tar.gz
	cp -v NAMESPACE $(TMPDIR)/$(RPKG)-$(GIT_TAG)
	install -d $(TMPDIR)/$(RPKG)-$(GIT_TAG)/man
	cp -v man/*.Rd $(TMPDIR)/$(RPKG)-$(GIT_TAG)/man
	cd $(TMPDIR)/$(RPKG)-$(GIT_TAG); "${R_HOME}/bin/R" --slave --file=tools/make-ds.R
	cd $(TMPDIR); NOT_CRAN=false "${R_HOME}/bin/R" CMD build $(RPKG)-$(GIT_TAG) --no-build-vignettes --no-manual
	rm -rf $(TMPDIR)/$(RPKG)-$(GIT_TAG)
	mv $(TMPDIR)/$(RPKG)_$(PKG_VERSION).tar.gz build/$(RPKG)-source.tar.gz
	touch build/r-source-fast

build/r-source-release : $(BIN_OBJS) $(DOC_OBJS) $(SRCS) inst/sbc/sbc_report.html
	install -d build
	git archive --format=tar.gz --prefix $(RPKG)-$(GIT_TAG)/ HEAD > build/$(RPKG)-$(GIT_TAG).tar.gz
	rm -rf build/$(RPKG)-$(GIT_TAG)
	cd build; tar xf $(RPKG)-$(GIT_TAG).tar.gz
	cp -v NAMESPACE build/$(RPKG)-$(GIT_TAG)
	install -d build/$(RPKG)-$(GIT_TAG)/inst/doc
	cp -v inst/doc/$(RPKG).pdf build/$(RPKG)-$(GIT_TAG)/inst/doc
	cp -v inst/sbc/sbc_report.html build/$(RPKG)-$(GIT_TAG)/inst/sbc/sbc_report.html
	cd build/$(RPKG)-$(GIT_TAG); "${R_HOME}/bin/R" --slave --file=tools/make-ds.R
	install -d build/$(RPKG)-$(GIT_TAG)/man
	cp -v man/*.Rd build/$(RPKG)-$(GIT_TAG)/man
	# set NOT_CRAN=true to get vignettes render with full sampling
	cd build; NOT_CRAN=true $(RCMD) CMD build --compact-vignettes=both $(RPKG)-$(GIT_TAG)
	#cd build; NOT_CRAN=false "${R_HOME}/bin/R" CMD build $(RPKG)-$(GIT_TAG) --no-build-vignettes --no-manual
	rm -rf build/$(RPKG)-$(GIT_TAG)
	cd build; $(MD5) $(RPKG)-$(GIT_TAG).tar.gz > $(RPKG)-$(GIT_TAG).md5
	cd build; $(MD5) $(RPKG)_$(PKG_VERSION).tar.gz > $(RPKG)_$(PKG_VERSION).md5
	touch build/r-source-release


# Build all HTML manuals
html-man: $(HTML_DOC_DIR) $(HTMLS)
	@echo "HTML manuals are in $(HTML_DOC_DIR)/"

# Ensure output directory exists
$(HTML_DOC_DIR):
	@mkdir -p $(HTML_DOC_DIR)

PHONY += r-source-release
r-source-release : build/r-source-release

PHONY += check-bib

PHONY += binary
binary : NAMESPACE src/package-binary

PHONY += derived
derived : NAMESPACE $(BIN_OBJS) $(DOC_OBJS)

PHONY += r-source-check
r-source-check : r-source
	cd build; tar xvzf $(RPKG)-source.tar.gz
	cd build; time NOT_CRAN=true $(RCMD) CMD check $(RPKG)

PHONY += r-source-release-check
r-source-release-check : r-source-release
	cd build; tar xvzf $(RPKG)_$(PKG_VERSION).tar.gz
	cd build; time NOT_CRAN=true $(RCMD) CMD check $(RPKG)

PHONY += r-source-release-check
r-source-cran-check : r-source-release
	cd build; tar xvzf $(RPKG)_$(PKG_VERSION).tar.gz
	cd build; time NOT_CRAN=false $(RCMD) CMD check --as-cran $(RPKG)

build/installed/$(RPKG)/DESCRIPTION : build/r-source-fast
	rm -rf build/installed
	install -d build/installed
	cd build; $(RCMD) CMD INSTALL --library=./installed --no-docs --no-multiarch --no-test-load --no-clean-on-error $(RPKG)-source.tar.gz

docs/index.html : doc $(SRCS)
	cp -f man-roxygen/start-example.R man-roxygen/start-example.R.slim.bak; \
	cp -f man-roxygen/start-example-full.R man-roxygen/start-example.R; \
	"${R_HOME}/bin/Rscript" -e 'roxygen2::roxygenize(roclets="rd")'; \
	status=0; NOT_CRAN=true $(RCMD) -e 'pkgdown::build_site()' || status=$$?; \
	mv -f man-roxygen/start-example.R.slim.bak man-roxygen/start-example.R; \
	"${R_HOME}/bin/Rscript" -e 'roxygen2::roxygenize(roclets="rd")'; \
	exit $$status

PHONY += pkgdown
pkgdown: docs/index.html

# Reverse dependency checks.
# REVDEP_WORKERS: reverse deps checked in parallel (each in its own subprocess).
# REVDEP_JOBS: C++ compile threads per package build (-jN). Keep
# REVDEP_WORKERS * REVDEP_JOBS near your core count and watch RAM: Stan/rstan
# builds are memory hungry.
REVDEP_WORKERS ?= 6
REVDEP_JOBS ?= 1

# Local run against the current working tree (includes uncommitted changes).
# Prerequisites make the source tree buildable/installable by revdepcheck:
# NAMESPACE + man/*.Rd (via NAMESPACE), compiled Stan src/ and R/sysdata.rda
# (via BIN_OBJS). The PDF manual/vignettes are intentionally omitted:
# revdepcheck builds with --no-manual --no-build-vignettes.
PHONY += revdepcheck
revdepcheck: NAMESPACE $(BIN_OBJS)
	$(RCMD) -e 'if (!requireNamespace("revdepcheck", quietly=TRUE)) pak::pak("r-lib/revdepcheck")'
	MAKEFLAGS="-j$(REVDEP_JOBS)" $(RCMD) -e 'revdepcheck::revdep_check(num_workers = $(REVDEP_WORKERS))'

# Run on GitHub's standard runners via workflow_dispatch. Uses the *pushed* tip
# of the current branch, NOT your local tree: commit and push before running.
PHONY += revdepcheck-ci
revdepcheck-ci:
	gh workflow run revdepcheck.yaml --ref "$$(git rev-parse --abbrev-ref HEAD)"
	sleep 5
	gh run watch --exit-status
	gh run download -n revdep-results || true

PHONY += dev-install
dev-install: build/installed/$(RPKG)/DESCRIPTION

PHONY += test-all
test-all : $(R_TEST_OBJS)

PHONY += testfast-all
testfast-all : $(R_TESTFAST_OBJS)

PHONY += retestfast-all
retestfast-all : clean-test $(R_TESTFAST_OBJS)

PHONY += retest-all
retest-all : clean-test $(R_TEST_OBJS)

PHONY += test-fixtures
test-fixtures : $(FIXTURE_OBJS)

PHONY += clean-fixtures
clean-fixtures :
	rm -f $(FIXTURE_OBJS)

PHONY += check-winbuilder-devel
check-winbuilder-devel : r-source-release
	cd build; $(RCMD) -e 'target <- tempdir()' \
			  -e 'untar("$(RPKG)_$(PKG_VERSION).tar.gz", exdir=target)' \
			  -e 'devtools::check_win_devel(pkg=file.path(target, "$(RPKG)"))'

PHONY += check-winbuilder-release
check-winbuilder-release : r-source-release
	cd build; $(RCMD) -e 'target <- tempdir()' \
			  -e 'untar("$(RPKG)_$(PKG_VERSION).tar.gz", exdir=target)' \
			  -e 'devtools::check_win_release(pkg=file.path(target, "$(RPKG)"))'

PHONY += check-winbuilder-oldrelease
check-winbuilder-oldrelease : r-source-release
	cd build; $(RCMD) -e 'target <- tempdir()' \
			  -e 'untar("$(RPKG)_$(PKG_VERSION).tar.gz", exdir=target)' \
			  -e 'devtools::check_win_oldrelease(pkg=file.path(target, "$(RPKG)"))'

PHONY += check-winbuilder
check-winbuilder : check-winbuilder-devel check-winbuilder-release check-winbuilder-oldrelease

#$(DIR_OBJ)/%.o: %.c $(INCS)
#    mkdir -p $(@D)
#    $(CC) -o $@ $(CFLAGS) -c $< $(INC_DIRS)

PHONY += clean
clean: clean-fixtures
	rm -rf build/*
	rm -f man/*.Rd
	rm -f NAMESPACE
	rm -f inst/doc/$(RPKG).pdf
	rm -f src/$(RPKG).so
	rm -f src/*.o
	rm -f man/package-doc
	rm -f src/package-binary
	rm -f R/sysdata.rda
	rm -f demo/*.html
	rm -f vignettes/*.html
	rm -f vignettes/*.docx
	rm -rf .Rd2pdf*
	rm -f $(R_TEST_OBJS)
	rm -f $(R_TESTFAST_OBJS)
	rm -f R/stanmodels.R

clean-test:
	rm -f $(R_TEST_OBJS)
	rm -f $(R_TESTFAST_OBJS)

PHONY += doc
doc: $(DOC_OBJS)

PHONY += echoes
echoes:
	@echo "INC files: $(INCS)"
	@echo "SRC files: $(SRCS)"
	@echo "OBJ files: $(OBJS)"

##
# Debug target that allows you to print a variable
##
print-%  : ; @echo $* = $($*)


.PHONY = $(PHONY)
