# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_inv_logit_fast <- function(l) {
    .Call(`_OncoBayes2_log_inv_logit_fast`, l)
}

log1m_exp_max0_fast <- function(l) {
    .Call(`_OncoBayes2_log1m_exp_max0_fast`, l)
}

